# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tracker-ical}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Niels Meersschaert"]
  s.date = %q{2011-04-13}
  s.description = %q{Get your iterations and releases in iCalendar format}
  s.email = %q{niels@meerwerks.com}
  s.extra_rdoc_files = [
    "CHANGELOG.rdoc",
    "README.rdoc",
    "VERSION"
  ]
  s.files = [
    ".document",
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/pivotal-tracker/story.rb",
    "lib/tracker-ical.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/tracker-ical_spec.rb",
    "tracker-ical.gemspec"
  ]
  s.homepage = %q{http://github.com/nielsm/tracker-ical}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Pivotal Tracker meets iCal}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/tracker-ical_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<icalendar>, [">= 1.1.6"])
      s.add_runtime_dependency(%q<pivotal-tracker>, [">= 0.2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<icalendar>, [">= 1.1.6"])
      s.add_dependency(%q<pivotal-tracker>, [">= 0.2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<icalendar>, [">= 1.1.6"])
    s.add_dependency(%q<pivotal-tracker>, [">= 0.2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.10"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

