# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tracker-ical}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Niels Meersschaert"]
  s.date = %q{2010-07-10}
  s.description = %q{Get your iterations and releases in iCalendar format}
  s.email = %q{niels@meerwerks.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/tracker-ical.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tracker-ical_spec.rb",
     "tracker-ical.gemspec"
  ]
  s.homepage = %q{http://github.com/nielsm/tracker-ical}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Pivotal Tracker meets iCal}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/tracker-ical_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<icalendar>, [">= 1.1.5"])
      s.add_runtime_dependency(%q<pivotal-tracker>, [">= 0.2.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<icalendar>, [">= 1.1.5"])
      s.add_dependency(%q<pivotal-tracker>, [">= 0.2.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<icalendar>, [">= 1.1.5"])
    s.add_dependency(%q<pivotal-tracker>, [">= 0.2.0"])
  end
end

